/* The story plan: every slide, in order. Slides without a module render as blueprint placeholders until built. */
Deck.plan([
  /* ---- act 1: the stakes */
  { id: 'title', section: 'why', t: 'Title', title: 'From a weather station to one data bank', st: 'none', short: 1 },
  { id: 'question', section: 'why', t: 'Safe to work now?', title: 'Is it safe to work right now?', st: 'live', short: 1 },
  { id: 'badges', section: 'why', t: 'Claim badges', title: 'Every claim wears a badge', st: 'none' },
  { id: 'map', section: 'why', t: 'The story map', title: 'The story map', st: 'none' },
  { id: 'stakes', section: 'why', t: 'What a wrong call costs', title: 'What a wrong call costs: lives and hours', st: 'stat', short: 1, brief: 'Real numbers on heat, lightning and gas, each with publisher and year.', shows: ['Heat stress: workers exposed, deaths, hours lost', 'Lightning: deaths and injuries a year', 'Gas and confined spaces: deaths and the limits', 'Counters count up. Every number shows publisher and year.'], needs: ['web numbers S1 to S4'] },
  { id: 'chain', section: 'why', t: 'Heat to cost chain', title: 'From heat to cost: the chain', st: 'stat', brief: 'How hot hours become lost hours, injuries and money. Every link carries a published coefficient.', shows: ['Hot hours reduce work capacity (published curve)', 'Lost hours become cost', 'Heat raises injury risk; injuries become deaths and cost', 'What prevention returns per dollar'], needs: ['relations model'] },
  /* ---- act 2: the conversion */
  { id: 'before', section: 'convert', t: 'Before: standalone', title: 'Before: a weather station on its own', st: 'code', brief: 'One product in two parts: a backend and a module inside the portal.', shows: ['May 2025: the backend is born', 'A legacy module inside the portal monorepo', 'First production reading, 1 May 2025 (internal cost doc)', 'One product, one page, one audience'], needs: ['C1 conversion history', 'C2 weather path'] },
  { id: 'timeline', section: 'convert', t: 'Six eras, 497 days', title: 'Six eras, 497 days', st: 'code', short: 1, brief: 'An animated timeline from the first backend commit to build 1.0.7.', shows: ['Eras: standalone, extraction, answer-first, rename, products land, 1.0', 'Commits per era: backend 447, front end 348', 'Rename to 1.0 in 37 days', 'Each milestone lights up in order'], needs: ['C1'] },
  { id: 'shipped', section: 'convert', t: 'Three products', title: 'One portal area, three products', st: 'live', short: 1 },
  { id: 'renameday', section: 'convert', t: 'Rename day', title: 'Rename day: one name, 260 files', st: 'code', brief: 'The day the app became Connected Environment, before and after.', shows: ['24 Aug: the app is renamed connected-environment', '260 files move under one product folder', '27 Aug: the backend follows with 345 files', 'A tree that morphs from before to after'], needs: ['C1'] },
  { id: 'status', section: 'convert', t: 'Where it stands', title: 'Where it stands', st: 'code', short: 1, brief: 'Live, in code, in test, planned, vision: the honest status board.', shows: ['Seen live on production', 'In code, deploy not verified', 'In test only', 'Planned and vision', 'Shared: shell, menu, backend, view permission. Not shared: rules, audit trail.'], needs: ['C1', 'release kit'] },
  { id: 'build', section: 'convert', t: 'The build in numbers', title: 'The build in numbers', st: 'code', brief: 'What was built, counted from the code.', shows: ['3 products, 6 front end feature folders', '28 controllers, 67 endpoints, 7 background services', '43 migrations, 31 tables, 33 MCP tools', 'Odometer counters with the command behind each'], needs: ['C1', 'C5'] },
  /* ---- act 3: the paths of readings */
  { id: 'flow', section: 'tech', t: 'Paths on one page', title: 'The path of every reading, today', st: 'code', short: 1 },
  { id: 'platform', section: 'tech', t: 'The platform around it', title: 'The platform around Connected Environment', st: 'code', brief: 'The services CE already talks to, and the ones it could.', shows: ['Mesh ingest, domain services, micro-apps', 'Observation Manager and notification rules', 'Location, zones and the safety service', 'Permits and equipment live in separate services'], needs: ['C6 ecosystem'] },
  { id: 'flow-weather', section: 'tech', t: 'Weather path', title: 'Weather: from a sensor head to a pixel', st: 'code', short: 1, brief: 'Ten hops, each one lit in turn.', shows: ['The 34-byte frame, the 29-column row', 'What each hop adds: decode, scale, heat index, band, verdict', 'The page asks again every 60 seconds', 'Danger episodes leave through the outbox'], needs: ['C2'] },
  { id: 'flow-lightning', section: 'tech', t: 'Lightning path', title: 'Lightning: silence is never clear', st: 'code', brief: 'A backup that never reads silence as safe.', shows: ['The warning unit decides; WakeCap is the backup', 'Two queues, each with a dead-letter queue', 'Stale after four missed heartbeats, swept every 5 s', 'Only green is safe'], needs: ['C3'] },
  { id: 'flow-gas', section: 'tech', t: 'Gas path', title: 'Gas: asked every 45 seconds', st: 'code', brief: 'No mesh, no Modbus: the vendor cloud, polled.', shows: ['One call returns the whole fleet', 'A reading over the High alarm opens an alert', 'Four critical alert types', 'Acknowledge and close stay in WakeCap'], needs: ['C4'] },
  { id: 'provenance', section: 'tech', t: 'Where numbers come from', title: 'Where every number on screen comes from', st: 'code', brief: 'Each number on the page, tagged device, computed, policy or user.', shows: ['Heat index, band, verdict, readiness, limits', 'Origin tag on every number', 'File and formula behind each one'], needs: ['C2', 'C3', 'C4'] },
  { id: 'alerts', section: 'tech', t: 'Alerts leave the screen', title: 'Alerts leave the screen', st: 'code', brief: 'From an alert to a person: outbox, Observation Manager, recipient rules.', shows: ['Outbox rows written with the alert', 'Dispatch to the Observation Manager', 'Recipient rules by source, zone, company', 'What is live, what is test, what is not evidenced'], needs: ['C3', 'C4', 'C6'] },
  /* ---- act 4: the data bank */
  { id: 'stores', section: 'bank', t: 'What is stored where', title: 'What is stored where', st: 'code', short: 1, brief: 'Three ponds today, with their real sizes.', shows: ['Sensors DB: 1.5 million weather readings (internal doc, Aug 2026)', 'CE Postgres: 31 tables, up from 10 in 70 days', 'Observation DB: events and recipients', 'No foreign keys across them'], needs: ['C5'] },
  { id: 'gaps', section: 'bank', t: 'Missing for prediction', title: 'What prediction would still need', st: 'code', brief: 'The honest gaps, read from the code.', shows: ['No forecast or trend code today', 'Verdicts stored as episodes since 20 Sep 2026', 'Gas history is stored; the screens say not yet', 'Weather observations carry no zone'], needs: ['C5', 'C6'] },
  { id: 'keys', section: 'bank', t: 'The join keys', title: 'The join keys that already exist', st: 'code', brief: 'Project, time, zone and device: where each key lives.', shows: ['Key by key, service by service', 'Workers, permits and equipment are keyed elsewhere', 'What a join would need'], needs: ['C5', 'C6'] },
  { id: 'pool', section: 'bank', t: 'The pool', title: 'From three ponds to one pool', st: 'vision', short: 1 },
  /* ---- act 5: what the bank enables (vision) */
  { id: 'predict', section: 'future', t: 'Predict the window', title: 'Predict: forecast the window', st: 'vision', short: 1, brief: 'A forecast of the heat and storm windows, with published evidence for early warning.', shows: ['A heat-index forecast curve with safe windows shaded', 'Storm approach and warning lead time', 'What published early-warning systems achieved', 'Vision. No dates.'], needs: ['web numbers S7, S2'] },
  { id: 'plan', section: 'future', t: 'Suggested work plans', title: 'Plan: suggested work plans', st: 'vision', brief: 'Tasks placed into the cool windows; a person approves.', shows: ['Heavy tasks in cool windows', 'Work and rest cycles from the policy', 'A person approves every plan', 'Published evidence for shifted hours'], needs: ['web numbers S1, S7'] },
  { id: 'lives', section: 'future', t: 'Save-lives loop', title: 'Save lives: the closed loop', st: 'vision', brief: 'Sense, predict, decide, notify, act.', shows: ['The loop, step by step', 'Existing today: Observation Manager and recipient rules', 'Lead times from published systems', 'A person stays in charge'], needs: ['web numbers S7', 'C6'] },
  { id: 'permits', section: 'future', t: 'Permits meet weather', title: 'Work permits meet the weather', st: 'vision', short: 1, brief: 'A permit gate that checks the conditions before work starts.', shows: ['Hot work: gas test and the LEL limit', 'Confined space: the oxygen window', 'Height and lifting: wind and lightning', 'The Digital Work Permit service already pushes six permit types to the Observation Manager'], needs: ['web numbers S3, S5', 'C6'] },
  { id: 'equipment', section: 'future', t: 'Equipment meets weather', title: 'Equipment meets the weather', st: 'vision', brief: 'Stand-down rules from wind, lightning and heat.', shows: ['Crane wind stand-down', 'Lightning stand-down', 'Heat and operator fatigue', 'Equipment telemetry already exists: GPS and violations'], needs: ['web numbers S5', 'C6'] },
  { id: 'streams', section: 'future', t: 'Four data streams', title: 'One platform, four data streams', st: 'vision', brief: 'Environment, workforce, permits and equipment, joined.', shows: ['What each stream adds', 'Questions only a join can answer', 'Insights that cross streams'], needs: ['C5', 'C6'] },
  /* ---- act 6: lives and cost */
  { id: 'calc', section: 'numbers', t: 'Your-site calculator', title: 'Your site, published rates', st: 'stat', short: 1, brief: 'An interactive calculator driven by published rates. An illustration, never a WakeCap result.', shows: ['Sliders: workers, hours, hot days', 'Published rates drive the result', 'Switch SAR or USD', 'Every coefficient shows its source'], needs: ['relations model'] },
  { id: 'relations', section: 'numbers', t: 'Relations, with numbers', title: 'The relations, with numbers', st: 'stat', brief: 'The chain from hot hours to lives and money, with sourced coefficients.', shows: ['Cause to effect, link by link', 'Returns on prevention', 'What is known and what is not'], needs: ['relations model'] },
  /* ---- act 7: next, and sources */
  { id: 'roadmap', section: 'next', t: 'Roadmap, no dates', title: 'What we build next', st: 'plan', short: 1, brief: 'By capability, no dates: foundations, predictions, integrations.', shows: ['Foundations: store everything, join keys', 'Predictions', 'Integrations', 'A ladder from live to vision'], needs: ['C1', 'C5', 'C6'] },
  { id: 'close', section: 'next', t: 'Close: lives first', title: 'One data bank. One answer. Lives first.', st: 'none', short: 1, brief: 'The story in one sentence, then questions.', shows: ['One data bank', 'One answer on site', 'Lives first'], needs: [] },
  { id: 'sources', section: 'appendix', t: 'Sources', title: 'Every number, its source', st: 'stat', brief: 'The table of every published number, its publisher, year and verification result.', shows: ['Publisher, title, year, link', 'Verified, partial or unverified', 'Which slide uses it'], needs: ['all web numbers'] },
  { id: 'limits', section: 'appendix', t: 'What we do not claim', title: 'What we do not claim', st: 'none', brief: 'The honest edges of this story.', shows: ['No WakeCap outcomes', 'No dates', 'No safety guarantees', 'The gaps we know'], needs: [] },
]);
